# Generated by Django 5.0.9 on 2025-02-10 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('Special_status', 'Can read all books')]},
        ),
    ]
